config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :restaurants

  get 'restaurants', to: 'restaurants#index'


  get 'restaurants/new', to: 'restaurants#new'

  get 'restaurants/:id', to: 'restaurants#show', as: 'restaurant'

  post 'restaurants', to: 'restaurants#create'

  get 'restaurants/:id/edit', to: 'restaurants#edit', as: 'edit_restaurant'

  patch 'restaurants/:id', to: 'restaurants#update'

  delete 'restaurants/:id', to: 'restaurants#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ['chinese', 'italian', 'japanese', 'french', 'belgian'] }


end

app/models/review.rb
class Review < ApplicationRecord
  validates :content, presence: true
  validates :ratting, inclusion: { in: [1, 2, 3, 4, 5] }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurants_path
  end


  def edit
  end

  def update

    @restaurant.update(restaurant_params)
    redirect_to restaurants_path
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end


  private


  def set_restaurant
    @restaurant = restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :found_on, :alive, :species)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name  %>
  <%= f.label :address %>
  <%= f.text_field :address%>
  <%= f.label :phone %>
  <%= f.date_field :phone %>
  <%= f.label :category %>
  <%= f.text_field :category %>
  <%= f.label :reviews %>
  <%= f.check_box :reviews %>
  <%= f.submit %>

<% end %>

app/views/restaurants/edit.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h1>Here's all the restaurants:</h1>

<ul>
<% @restaurants.each do |restaurant| %>
  <li><%= link_to restaurant.name, restaurant_path(restaurant.id) %></li>
<%  end %>
</ul>


<%= link_to 'Create a new restaurant', restaurants_new_path %>

app/views/restaurants/new.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<h2>Address: <%= @restaurant.address %></h2>
<h2>Phone: <%= @restaurant.phone %></h2>
<h2>Category: <%= @restaurant.category %></h2>




<%= link_to 'Edit', edit_restaurant_path(@restaurant) %>

<%= link_to 'Back', restaurants_path  %>

<%= link_to 'Delete', restaurant_path(@restaurant), method: :delete, data: {confirm: "Iupiii!!!!"} %>